### ISSUE TITLE
`SWITCH_TRACKING_PIXEL` not being respected

### ISSUE THREAD

**Issue by jpetto** [mozmeao/www-config#110]
Setting `SWITCH_TRACKING_PIXEL` to a truthy value should [add the configured pixel sources to the `CSP_IMG_SRC` list](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L1350-L1352). The switch is enabled for both stage and prod, yet the configured pixel sources (only `ad.doubleclick.net`, I believe) are not allowed in CSP ([stage](https://cspvalidator.org/#url=https://www.allizom.org), [prod](https://cspvalidator.org/#url=https://www.mozilla.org)).

Perhaps [`ENABLED_PIXELS`](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L1347) is set incorrectly?

This issue is impacting tracking on `/download/thanks/`.

**Comment by jpetto** [comment]
@pmclanahan or @jgmize - Can you take a look when all-hands allows?

**Comment by jpetto** [comment]
FWIW, Alex and I tried a config push to stage (#109) as a fix, but no luck.

**Comment by pmac** [comment]
Okay. You have stumbled across quite the edge-case. This "switch" is being used as a normal config value and a waffle switch. So in this case it needs to be configured in the "static" config files (e.g. `configs/bedrock-prod.env`) because it needs to be available in the django settings as well as in the templates. I'll make that change now.

**Comment by ejregithub** [comment]
@pmac - The resolution is clear here but the reason the edge case came into play is not.  The issue (dip in reporting of clicks) was first noted on 5/18.  Change to switch, change to django settings?  Someone will ask, so I'm doing so now before they do.  ;)

**Comment by pmac** [comment]
I have it on my list to better document this, but basically we have 2 types of configuration values in this repo. You can read about them in [the docs](https://mozmeao.github.io/www-config/). The issue here was that a waffle switch (or Dynamic config) was being also used and referenced as a traditional configuration value (Static config) as well. So when the value was changed one part of it would work and another wouldn't.

Basically the difference is that the "dynamic" values (mostly waffle switches) aren't available at app startup time, which is when the config values are set. And even if these dynamic values are available later and even change later they're only read at app startup time, so the app will remain unaware. Calls to `switch()` in the templates and views are dynamic because they're read fresh on every request to the page, so the value you can be in the dynamic files and can change without a deployment or restart of the app.
