### ISSUE TITLE
Remove auto-generated docs and update static docs content

### ISSUE THREAD

**Issue by pmac** [mozmeao/www-config#239]
The method for updating environment variables on the bedrock servers has changed and the docs need to be updated to reflect that.

I believe the [auto-generated docs](https://mozmeao.github.io/www-config/configs/) aren't providing much value over just looking at the files, and as we move from Jenkins to GitLab CI it is work to make that generation happen in the new system. 

Once the auto-generation of the config values is no longer a requirement, we can update the docs process to just be plain [GH Pages](https://pages.github.com/) and not require any further automation on our part.

/cc @jgmize @alexgibson

**Comment by pmac** [comment]
@jgmize should these updated docs reference the `git-sync-operator` branch for now, or just go ahead with the new way of updating things in the #237 PR?

**Comment by jgmize** [comment]
Let's consider the `git-sync-operator` branch deprecated as of now and plan on #237 merging to master in the near future. I'm still dealing with failing tests due to network issues in Frankfurt (where the current AWS gitlab-runner-0 is) but I believe I'll be able to work around those by moving the test executions to a different runner and unblock that soon.

**Comment by pmac** [comment]
Sounds good. We can do the docs changes after your PR is merged.
